apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/amirsha619/argo-todo-app.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
